CREATE DATABASE  IF NOT EXISTS `svetaalissa` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `svetaalissa`;


CREATE TABLE `company` (
  `COMPANY_ID` int(11) NOT NULL,
  `COMPANY_NAME` varchar(50) NOT NULL,
  `PASSWORD` varchar(50) NOT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`COMPANY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `customer` (
  `CUSTOMER_ID` int(11) NOT NULL,
  `CUSTOMER_NAME` varchar(50) NOT NULL,
  `PASSWORD` varchar(50) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `coupon` (
  `COUPON_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` int(11) NOT NULL,
  `TITLE` varchar(50) NOT NULL,
  `START_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `END_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `AMOUNT` int(11) NOT NULL,
  `TYPE` varchar(50) NOT NULL,
  `MESSAGE` varchar(200) NOT NULL,
  `PRICE` double NOT NULL,
  `IMAGE` varchar(200) NOT NULL,
  PRIMARY KEY (`COUPON_ID`,`COMPANY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=98766 DEFAULT CHARSET=utf8;


CREATE TABLE `customer_coupon` (
  `CUSTOMER_ID` int(11) NOT NULL,
  `COUPON_ID` int(11) NOT NULL,
  UNIQUE KEY `unique_index` (`CUSTOMER_ID`,`COUPON_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;